### PR TITLE
Realtime stdout printing for commands (#217) 

### PR DESCRIPTION
**Pull request by spurnvoj**

### CODE REVIEW

**Comment by jacebrowning** [comment]
@spurnvoj Thanks for putting this together! Seeing realtime output would be great. Perhaps this could even be the default behavior?

What's the best way to try out this functionality?

**Comment by spurnvoj** [comment]
Hi, sure it can be :) My plan at the beginning was to have the same output, for example, for `git clone --progress ...` command that shows progress in realtime. Like this output:
```bash
user@athena:~/cloj/src$ git clone git://git.boinkor.net/slime.git
Initialized empty Git repository in /home/user/cloj/src/slime/.git/
remote: Counting objects: 15936, done.
remote: Compressing objects: 100% (5500/5500), done.
Receiving objects:  28% (4547/15936), 3.16 MiB | 165 KiB/s
```
 Unfortunately, it is not easy to parse the output and print it inside of scripts. At least I managed to print stdout as it comes. 

You can see a difference in behavior on this example of **gitman.yaml**. In the previous version, the output of calling scripts command was printed once `git submodule update --init --recursive --depth 1` finished. With the current version, you should see the output as is produced. 
```yaml
location: .gitman
sources:
- name: px4_firmware
  type: git
  repo: https://github.com/ctu-mrs/px4_firmware.git
  sparse_paths:
  -
  rev: v1.10.1
  link: ros_packages/px4_firmware
  scripts:
  - git submodule update --init --recursive --depth 1
groups: []
```

**Comment by jacebrowning** [comment]
@spurnvoj if you rebase on `origin/develop`, dependency installation on CI should be fixed (https://github.com/jacebrowning/gitman/pull/220).

**Comment by spurnvoj** [comment]
@jacebrowning rebase should be done, but it still fails. Can you tell me why?

**Comment by jacebrowning** [comment]
@spurnvoj some of the CI checks are failing, specifically code formatting. There are instructions to run these checks locally here: https://github.com/jacebrowning/gitman/blob/develop/CONTRIBUTING.md#continuous-integration

**Comment by spurnvoj** [comment]
@jacebrowning I missed that part, but it is fixed now. The tests are passing for Python 3.8.

**Comment by spurnvoj** [comment]
@jacebrowning Python 3.7 failed on the installation of pip (see [log](https://travis-ci.org/github/jacebrowning/gitman/jobs/710895415)). Can you please run it again? maybe it will help

**Comment by jacebrowning** [comment]
@spurnvoj The build is passing now.

Are there any cases where `_show=False` that we cannot simply infer `_show_stdout=False`? Do these actually need to be distinct parameters?

**Comment by spurnvoj** [comment]
There is the one case.. see https://github.com/jacebrowning/gitman/pull/219/files#diff-a0f942cdd578aa8d72f08a298faa1763R183 ... without that, you will sometime see that you are on detached HEAD (depends if the commit matches some branch head)

**Comment by spurnvoj** [comment]
but when `_show=False` then is everytime `_show_stdout=False` too

**Pull request merged**
