### PR TITLE
better Debugging Support for VsCode and "unlock"-operation

### PR DESCRIPTION
**Pull request by daniel-brosche**
Hello,

i'm interessted in gitman and I have added some functionality and also improved VsCode debugging support.

Best Regards, Daniel...

### CODE REVIEW

**Comment by jacebrowning** [comment]
Thanks for the contribution!

A few questions and comments:

- Can you explain the cases where the changes to `gitman/__main__.py` are needed?

- What are the expected use cases for the `unlock` command? I'm not aware of a similar concept in other package managers.

- These changes are more likely to get merges as separate PRs.

**Comment by daniel-brosche** [comment]
Hello,

the modifications are needed to launch/debug gitman (__main__.py) in Visual Studio Code IDE. 
I have attached my launch configuration. 
[.vscode.zip](https://github.com/jacebrowning/gitman/files/608558/default.vscode.zip)

Over this way I can easily debug gitman by pressing F5.
Without this modification I had problems to resolve "from gitman.cli import main".

The idea behind the unlock operation is to provide a corresponding oposite operation to lock. As far as I know when I use look operation then the current checked out commits are stored in the .gitman.yml file. 
When I execute the install operation then this sources_locked fields are used instead of the sources fields. 
From this perspective the install operation is locked to the sources_locked fields. 
Locally I just want to use the install operation to install the last verfied "non broken" state that will be determined on the CI Server by using update and lock operation.
Additionally I want to unlock the install operation to localy verify broken states that are detected by the CI without the need to manually edit the file.


Best regards...

**Comment by daniel-brosche** [comment]
Should I split the PR?
What's the problem of travis?

**Comment by jacebrowning** [comment]
> Should I split the PR?

If you make the Visual Studio changes in another PR, I'd be happy to merge that right away.

> What's the problem of travis?

The linter is reporting some inconsistencies. Just run `$ make ci` locally or invoke `pep8` from your IDE.

> Additionally I want to unlock the install operation to localy verify broken states that are detected by the CI without the need to manually edit the file.

Is a new command really needed for this? What's wrong with this workflow:

1. `gitman update --lock` - downloads the latest code and updates the `sources_locked`
2. Run your tests
  - If tests pass, commit `.gitman.ym`
  - If tests fail, fix your local code to work with the newer dependency and/or update the dependency's code, then go back to 1

**Comment by daniel-brosche** [comment]
Not really needed as a must - more or less just a logic resp. theoretical aspect.

**Pull request closed without merging**
