### PR TITLE
Add clean command to only remove dependencies but not top level folder

### PR DESCRIPTION
**Pull request by DavidWatkins**
I have found that in my projects I'd need a function to only remove stale dependencies but not the top level folder. For example I want all my dependencies stored in a folder called src but don't want to delete src because I need to keep other files in the git repo at that location. I added a clean command to do this.

### CODE REVIEW

**Comment by jacebrowning** [comment]
@DavidWatkins Thanks for the proposal! I think this might work better as an option to the existing `uninstall` command rather that whole new command. Perhaps: `gitman uninstall --keep-location`?

**Comment by DavidWatkins** [comment]
@jacebrowning That's a good idea. I've updated the current commit to reflect your recommendation.

**Comment by jacebrowning** [comment]
@DavidWatkins The code looks good to me! The Windows tests _were_ passing on `develop`, so it's possible there might be some incompatible change here. Can you make any sense of the AppVeyor failures?

**Comment by DavidWatkins** [comment]
@jacebrowning I fixed the issue. Your 'source.identify' function cd's into the directory to get the cwd. I changed my implementation of config.get_top_level_dependencies to instead just concatenate config.location_path and the source.name variable to get the dependency to delete. I also configured scrutinizer to properly pass again.

**Comment by jacebrowning** [comment]
Released as `pip install gitman==1.5b1`.

**Pull request merged**
