### PR TITLE
Loop through all nested configs

### LINKED ISSUE #337: Nested projects are skipped
# Setup

```
cd /tmp
git clone https://github.com/jacebrowning/gitman-demo2 demo
cd demo
```

## Actual Behavior

```
pipx install --force gitman==3.5.1  # main
gitman install --no-scripts
```

```
Installing dependencies...

$ cd /private/tmp/demo

  $ cd fontawesome
  $ git checkout --force master

Installed 1 dependency
```

## Expected Behavior

```
pipx install --force gitman==3.5.2a1  # https://github.com/jacebrowning/gitman/pull/335
gitman install --no-scripts
```

```
Installing dependencies...

$ cd /private/tmp/demo

  $ cd fontawesome
  $ git checkout --force master

Installing nested dependencies...

$ cd /private/tmp/demo/level_1a

  $ cd framework
  $ git checkout --force Mk5-end-of-life

Installing nested dependencies...

$ cd /private/tmp/demo/level_1b/level_2

  $ cd trufflehog
  $ git checkout --force main

Installed 3 dependencies
```

### PR DESCRIPTION
**Pull request by jacebrowning**
Fixes #337 

---

@DavidWatkins can you remind me the purpose of the function I removed in this pull request? As far as I can tell [the alpha release from this branch](https://pypi.org/project/gitman/3.5.2a1/) is behaving as I expect in relation to nested configs but `main` is not.

### CODE REVIEW

**Comment by DavidWatkins** [comment]
@jacebrowning This was removing any configs that come in from any pulled dependencies but still allowed subdirectories to be included for aggregating configs. I would not remove it. What is the behavioral difference you are observing?

**Comment by jacebrowning** [comment]
@DavidWatkins I opened https://github.com/jacebrowning/gitman/issues/337 to show how to reproduce the behavioral difference.

**Comment by DavidWatkins** [comment]
@jacebrowning Ah I see. It's been a year and I cannot remember exactly why I wanted recursion over directories without automatically cloning those sub-dependency `gitman.yml` files, but with fresh eyes, it makes more sense to allow for this behavior. Go ahead and push this change and we'll make changes on our end to support the new workflow if it breaks anything.

**Comment by jacebrowning** [comment]
@DavidWatkins thanks for taking a look! I'll release this as `3.5.2` and please open an issue if you notice any strange behavior.

**Pull request merged**
